Fix failure due to PyObject version error
Reported:

========================================================================
==> Installing jeffreywildman/virt-manager/virt-manager
==> Patching
==> python3 -m venv --system-site-packages
/opt/homebrew/Cellar/virt-manager/3.2.0_4/libexec
==> /opt/homebrew/Cellar/virt-manager/3.2.0_4/libexec/bin/pip install -v
--no-deps --no-binary :all: --ignore-installed
/private/tmp/virt-manager--certifi-20210715-14749-4ogwsh/certifi-2021.5.30
==> /opt/homebrew/Cellar/virt-manager/3.2.0_4/libexec/bin/pip install -v
--no-deps --no-binary :all: --ignore-installed
/private/tmp/virt-manager--charset-normalizer-20210715-14749-tufesi/charset-normalizer
==> /opt/homebrew/Cellar/virt-manager/3.2.0_4/libexec/bin/pip install -v
--no-deps --no-binary :all: --ignore-installed
/private/tmp/virt-manager--idna-20210715-14749-1dtint7/idna-3.2
==> /opt/homebrew/Cellar/virt-manager/3.2.0_4/libexec/bin/pip install -v
--no-deps --no-binary :all: --ignore-installed
/private/tmp/virt-manager--libvirt-python-20210715-14749-bpb72i/libvirt-python-7.5.0
==> /opt/homebrew/Cellar/virt-manager/3.2.0_4/libexec/bin/pip install -v
--no-deps --no-binary :all: --ignore-installed
/private/tmp/virt-manager--pycairo-20210715-14749-1etdh6y/pycairo-1.20.1
==> /opt/homebrew/Cellar/virt-manager/3.2.0_4/libexec/bin/pip install -v
--no-deps --no-binary :all: --ignore-installed
/private/tmp/virt-manager--PyGObject-20210715-14749-10sxwp4/PyGObject-3.40.1
Last 15 lines from
/Users/rafaelreisr/Library/Logs/Homebrew/virt-manager/07.pip:
error: command '/opt/homebrew/Library/Homebrew/shims/mac/super/clang'
failed with exit code 1
Building wheel for PyGObject (PEP 517): finished with status 'error'
ERROR: Failed building wheel for PyGObject
Failed to build PyGObject
ERROR: Could not build wheels for PyGObject which use PEP 517 and
cannot be installed directly
Exception information:
Traceback (most recent call last):
File
"/opt/homebrew/Cellar/virt-manager/3.2.0_4/libexec/lib/python3.9/site-packages/pip/_internal/cli/base_command.py",
line 180, in _main
status = self.run(options, args)
File
"/opt/homebrew/Cellar/virt-manager/3.2.0_4/libexec/lib/python3.9/site-packages/pip/_internal/cli/req_command.py",
line 205, in wrapper
return func(self, options, args)
File
"/opt/homebrew/Cellar/virt-manager/3.2.0_4/libexec/lib/python3.9/site-packages/pip/_internal/commands/install.py",
line 360, in run
raise InstallationError(
pip._internal.exceptions.InstallationError:
Could not build wheels for PyGObject which use
PEP 517 and cannot be installed directly
Removed build tracker:
'/private/tmp/pip-req-tracker-nhy48g95'

Do not report this issue to Homebrew/brew or Homebrew/core!
)
========================================================================

Manually update venv enviroment before dep installations.

Signed-off-by: Su Yue <l@damenly.su>